services:
  - type: web
    name: woodfurnished-website
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn WoodFurnished.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: WoodFurnished.settings
      - key: PYTHON_VERSION
        value: 3.13
